import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { ThemeSwitcher } from "@/features/theme/ThemeSwitcher";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import "@/shared/styles/globals.css";
import LanguageSwitcher from "@/features/locale/LanguageSwitcher";

const jostSans = Jost({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${jostSans.className}  antialiased`}>
        <NextIntlClientProvider>
          {/*
          <ThemeSwitcher />
          <LanguageSwitcher />
          */}
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
